/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ConnectCode: (typeof import('./src/components/ConnectCode.vue'))['default']
    ImportRooms: (typeof import('./src/components/ImportRooms.vue'))['default']
    MaterialSymbolsDeleteRounded: (typeof import('./src/components/Icons/MaterialSymbolsDeleteRounded.vue'))['default']
    MaterialSymbolsSyncRounded: (typeof import('./src/components/Icons/MaterialSymbolsSyncRounded.vue'))['default']
    MingcuteCloseFill: (typeof import('./src/components/Icons/MingcuteCloseFill.vue'))['default']
    MingcuteMinimizeFill: (typeof import('./src/components/Icons/MingcuteMinimizeFill.vue'))['default']
    NAvatar: (typeof import('naive-ui'))['NAvatar']
    NButton: (typeof import('naive-ui'))['NButton']
    NButtonGroup: (typeof import('naive-ui'))['NButtonGroup']
    NConfigProvider: (typeof import('naive-ui'))['NConfigProvider']
    NDialogProvider: (typeof import('naive-ui'))['NDialogProvider']
    NGradientText: (typeof import('naive-ui'))['NGradientText']
    NIcon: (typeof import('naive-ui'))['NIcon']
    NMessageProvider: (typeof import('naive-ui'))['NMessageProvider']
    NModal: (typeof import('naive-ui'))['NModal']
    NModalProvider: (typeof import('naive-ui'))['NModalProvider']
    NPopconfirm: (typeof import('naive-ui'))['NPopconfirm']
    NPopover: (typeof import('naive-ui'))['NPopover']
    NQrCode: (typeof import('naive-ui'))['NQrCode']
    NScrollbar: (typeof import('naive-ui'))['NScrollbar']
    RoomListItem: (typeof import('./src/components/RoomListItem.vue'))['default']
    RouterLink: (typeof import('vue-router'))['RouterLink']
    RouterView: (typeof import('vue-router'))['RouterView']
    WinMenu: (typeof import('./src/components/WinMenu.vue'))['default']
  }
}
